doc.type.html
script
this.img=document.createelement(covid)
img.src=http://www.google.com/intl/en_com/images/logo_plain.png
src=documentgetelementbyid(header)
src.appendchild(this.img)
filename=covidstrings21gamecode.js
java.awt graphics 
<div id=header></div>
audio=new audio (audio_file mp3)
audio.play 
random button
new jbutton (set random color)
private final j button option button=
new  button (change color)
public fun with graphics(){
color panel=new j panel();
add (panel,center )
button panel
new j panel (flowlayout.center)
buttonpanel.add(randombutton);
random.button add actionlistener(new action listener)
override 
public actionperformed(actionevent e)
random r= newrandom();
colorpanel.setbackground(new color(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13)))
num teams
total players=players per team
if players per team=zero
return zero
else 
return math floor total players/players per team
teamsgrouping=(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)
buttonpanel.add(optionbutton);
optionbutton.add actionlistener(new action istener)
override 
public actionperformed(actionevent e)
color m=jcolorchooser.showdialog(funwithgraphics.this)
if(multi!=null)
color panel set.background(multi)
this.add(buttonpanel,borderlayout.south)
public static main(string [] args){
jframe f = new covid strings21()
f.set title(covid strings21)
f.set default closeoperation(jframe.exit_on_close);
f.setsize
f.set visible(true);
label id=lblscore<zero>label>
score=zero
if (mult == x*y)
[non-concatenated]
score+=ten
else:
score-=ten
if (mult == x*y)
[concatenated]
score+=twenty
else:
score-=twenty
lblscore=document.getelementbyid(lblscore)
lbl.score.inner html=score
public actionperformed(action event e) 
system.out print.in (next button clicked)
frame.add(next button);
frame set visible true
object {a:one,b:two,c:three,d:four,e:five,f:six,g:seven,h:eight}
keys object(team)
entries object entries(obj);
value object [team color]
covidstringsteam list21=[orange rna messengers ,turquoise waves ,green peacemakers,burgundy rebuilders ,red protein spikers ,indigo isos,magenta magnetizers ,yellow moxie]
covid strings phrase list21=[non-concatenated strings "while fluifying covid may be abhorrent keeping everything the same also doesnt make sense"
"that said testing for viruses as a whole can be expanded"
"another new habit can involve older adults getting an extra covid shot"
"mirai does not mean covid miracle"
"in terms of covid news there may be as many if not more languages than trump claims americans understand from immigrants to fully understand"
"light at the end of the tunnel is not just for angels to fly"
"this excludes recent cdc guidance saying that you no longer need5 days of isolation if infected"
"this includes clinical trials for long covid"
concatenated strings
"it"+"is"+"also"+"important"+"to"+"know"+"that"+"vaccine"+"myths"+"still"+"need"+"to"+"be"+"exposed"+"as"+"such"
"for"+"example"+"the"+"belief"+"that"+"vaccines"+"impact"+"fertility"+"is"+"false"
"the"+"belief"+"that"+"microchips"+"can"+"be"+"implanted"+"by"+"bill"+"gates"+"also"+"false"
"it"+"should"+"be"+"especially"+"easy"+"to"+"know"+"covid"+"cant"+"spread"+"on"+"5G"
"saying"+"it"+"does"+"creates"+"a"+"more"+"dangerous"+"virus"
"neither"+"alcohol"+"nor"+"chlorine"+"are"+"effective"+"treatments"
"you"+"might"+"actually"+"blame"+"more"+"severe"+"covid"+"on"+"the"+"alcohol"
"even"+"though"+"you"+"shouldnt"+"take"+"chlorine"+"for"+"treatment"+"chlorine"+"dioxide"+"may"+"work"+"on"+"surfaces"]
covidstrings21mathproblemslist=[ non-concatenated "if a poll found that32 percent of americans believe that5g towers through huawei are a side effect of taking the covid vaccine what percent dont"?,"if26 percent mildly believe what percent strongly believe"?,"if the margin of error 2.0185percent what is the range"?,"if the term jumbos was presented to535 americans if79 percent believe it means jumbo vaccines how many dont"?,"if 75 percent strongly believe it means jumbo vaccines what percent is mild?,if the margin of error is .775 percent what is the range"?
concatenated "if"+"a"+"study"+"found"+"that"+"nasal"+"vaccines"+"were"+"75"+"percent"+"more"+"likely"+"to"+"be"+"effective"+"at"+"preventing"+"severe"+"covid"+"than"+"the"+"current"+"generation"+"of"+"vaccines"+"which"+"only"+"work"+"50"+"percent"+"of"+"the"+"time"+"what"+"is"+"the"+"difference"?  
,"if"+"the"+"cdc"+"says"+"there"+"will"+"be"+"a"+"shipment"+"of"+"200,000"+"vaccines"+"coming"+"if"+"the"+"ratio"+"is"+"1"+"to"+"20"+"how"+"many"+"of"+"each"+"vaccine"+"is"+"there"?,"if"+"43"+"percent"+"agree"+"with"+"new"+"cdc"+"guidance"+"on"+"not"+"needing"+"5"+"days"+"of"+"isolation"+"how"+"many"+"disagree"?,"if"+"33"+"percent"+"strongly"+"agree"+"what"+"percent"+"is"+"mild"?,"if"+"the"+"margin"+"of"+"error"+"is"+"10.5"+"percent"+"what"+"is"+"the"+"range"?]
covid strings21multiplechoicelist=[1:a mexicans b  martians c languages d  moochers,2:a half-truths b cold cases c myths d models made by mullen,3:a covid b rsv c the pontiac g8 concept d callum motors,4:a bacteria resistant to antibiotics b fertility c an american suzuki jimny d a new nissan murano,5:a viruses b why neil gorsuch overturned his mothers victory c nyobolt d a new ford capri,6:a3g b2g c4g d5g ,6:a social security check b reminder about why evs are safe c window clings d covid shot,7:a jack dorsey b mark zuckerberg c bill gates d kash patel,
8:a mirai b clarity c freestyle d million dollar baby,9:a myth b twitter livestream c virus d chan for white supremacists,10:a starships b vampire bats c angels d airships,11:a12 days b5 days c101 days d9 days,12:a natos trump whisperer b wegovy c long covid d the last pontiac ever made,13:a chlorine b a bubble bath c windex d communism being the right thing in america,14:a booze b peds given to joe biden c brics d alcohol,
15:a monoxide b dioxide c trioxide d quadrivalent,16:a the first women president b vladimir putin c putin and his head investigator feuding d lauren daegals light of the world]
covid strings21 sentence =["covid would be even less of a miracle than putin and his head investigator feuding"]
covid strings scrambled phraselist21=["noires deen ratxe ovicd tosh","5"+"yads"+"fo"+"naltionsoi","afke"+"lilb"+"tages"+"croimhip"]
userin.select team
import meta.
class myclass
constructor(non-concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else
prompt 
log
myclass=new.myclass(concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else
prompt 
log
import syntax
public.boolean isscramble
if (s1.length())!=s2.length()or s3.length()
return false
if (s1.length()) ==s2 or s3 
return true
char[]arr1=s1.tochararray
char[]arr2=s2.tochararray
char [] arr3=s3.tochararray
arrays.sort (arr1)
arrays.sort(arr2)
arrays.sort(arr3)
if(!new string(arr1).equals(new string (arr2)))
return false
for(int i=1; i<s1.length();i++)} 
string11=s1.substring(0,i)
string12=s1.substring(i,s1.length()-i);
string 13=s1.substring(i,s1.length()-i());
string14=s1.substring(0,s1.length()-i s1.length());
strings21=s2.substring(0,i)
string22=s2.substring(0,s2.length()-i);
string23=s2.substring(0,s2.length()-i ());
string24=s2.substring(0,s2.length()-i s2.length());
string31=s3.substring(0,i)
string32=s3.substring(0,s3.length()-i)
string33=s3.substring(0,s3.length()-i());
string34=s3.substring(0,s3.length()-i s3.length());
substring(start,end)
userin.multiple choice
if selectedanswer==correct answer:
return true
else:
return false
if selectedanswer=not correct
return false
else 
return true
answer checker
scanner=new scanner(system.in)
string correct answer
string useranswer=scanner.nextline()
if useranswer.equals(correctanswer)
system.out.print.in(correct)
else:
system.out.printin(incorrect)
scanner.close
check winner:
if winner==true:
log(the winner is)
if winner==false:
log(no winner yet) 
if users team wins covid strings21 
console log users team wins covid strings21 
else
return game over
return filename




