doc.type.html
script
filename=covidstrings21gamecode.js
java.awt graphics 
this.img=document.createelement(covid)
img.src=http://www.google.com/intl/en_com/images/logo_plain.png
src=documentgetelementbyid(header)
src.appendchild(this.img)
<div id=header></div>
audio=new audio (audio_file mp3)
audio.play 
jbutton random button
new jbutton (set random color)
private final j button option button=
new j button (change color)
public fun with graphics(){
jpanel color panel=new j panel();
this add (panel,center )
jpanel button panel=
new j panel (flowlayout.center)
buttonpanel.add(randombutton);
random.button add actionlistener(new action listener)
override 
public actionperformed(actionevent e)
random r= newrandom();
colorpanel.setbackground(new color(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13)))
buttonpanel.add(optionbutton);
optionbutton.add actionlistener(new action istener)
override 
public actionperformed(actionevent e)
color m=jcolorchooser.showdialog(funwithgraphics.this)
if(multi!=null)
color panel set.background(multi)
This.Add(ButtonPanel,borderlayout.south)
public static main(string [] args){
jframe f = new covid strings21()
f.set title(covid strings21)
f.set default closeoperation(jframe.exit_on_close);
f.setsize
f.set visible(true);
label id=lblscore<zero>label>
score=zero
if (mult == x*y)
[non-concatenated]
score+=ten
else:
score-=ten
if (mult == x*y)
[concatenated]
score+=twenty
else:
score-=twenty
lblscore=document.getelementbyid(lblscore)
lbl.score.innerHTML=score
public actionperformed(action event e) 
system.out print.in (next button clicked)
frame.add(next button);
frame set visible true
object {a:one,b:two,c:three,d:four,e:five,f:six,g:seven,h:eight}
keys object(team)
Entries Object Entries(Obj);
Value Object [Team Color]
CovidstringsTeam List21=[Orange,Turquoise,Green,Burgundy,Red,Indigo,Magenta,Yellow]
Covid Strings Phrase List21=[Non-ConcatenatedWhile Fluifying Covid May Be Abhorrent Keeping Everything The Same Also Doesnt Make Sense
That Said Testing For Viruses As A Whole Can Be Expanded
Another New Habit Can Involve Older Adults Getting An Extra Covid Shot
Mirai Does Not Mean Covid Miracle
In Terms Of Covid News There May Be As Many If Not More Languages Than Trump Claims Americans Understand From Immigrants To Fully Understand 
Light At The End Of The Tunnel Is Not Just For Angels To Fly
This Excludes Recent CDC Guidance Saying That You No Longer Need5 Days Of Isolation If Infected
This Includes Clinical Trials For Long Covid
Concatenated
It+Is+Also+Important+To+Know+That+Vaccine+Myths+Still+Need+To+Be+Exposed+As+Such
For+Example+The+Belief+That+Vaccines+Impact+Fertility+Is+False
The+Belief+That+Microchips+Can+Be+Implanted+By+Bill+Gates+Also+False
It+Should+Be+Especially+Easy+To+Know+Covid+Cant+Spread+On+5G
Saying+It+Does+Creates+A+More+Dangerous+Virus
Neither+Alcohol+Nor+Chlorine+Are+Effective+Treatments
You+Might+Actually+Blame+More+Severe+Covid+On+The+Alcohol
Even+Though+You+Shouldnt+Take+Chlroine+For+Treatment+Chlorine+Dioxide+May+Work+On+Surfaces]
Covid Strings21MathProblemsList=[If A Poll Found That32 Percent Of Americans Believe That5g Towers Through Huawei Are A Side Effect Of Taking The Covid Vaccine What Percent Dont?, If26 Percent Mildly Believe What Percent Strongly Believe?, If The Margin Of Error 2.0185Percent What Is The Range?,If The Term Jumbos Was Presented To535 Americans If79 Percent Believe It Means Jumbo Vaccines How Many Dont?,If 75 Percent Strongly Believe It Means Jumbo Vaccines What Percent Is Mild?,If The Margin Of Error Is .775 Percent What Is The Range?if+a+study+found+that+nasal+vaccines+were+75+percent+more+likely+to+be+effective+at+preventing+severe+covid+than+the+current+generation+of+vaccines+which+only+work+50+percent+of+the+time+what+is+the+difference?  
,If+The+CDC+Says+There+Will+Be+A+Shipment+Of+200,000+Vaccines+Coming+If+The+Ratio+Is+1+To+20+How+Many+Of+Each+Vaccine+Is+There?,If+43+Percent+Agree+With+New+CDC+Guidance+On+Not+Needing+5+Days+Of+Isolation+How+Many+Disagree?,If+33+Percent+Strongly+Agree+What+Percent+Is+Mild?,If+The+Margin+Of+Error+Is+10.5+Percent+What+Is+The+Range?]
covid strings21multiplechoicelist=[1:a mexicans b  martians c languages d  moochers,2:a half-truths b cold cases c myths d models made by mullen,3:a covid b rsv c the pontiac g8 concept d callum motors,4:a bacteria resistant to antibiotics b fertility c an american suzuki jimny D A New Nissan Murano,5:A Viruses B Why Neil Gorsuch Overturned His Mothers Victory C Nyobolt D A New Ford Capri,6:A3g B2g C4g D5g ,6:A Social Security Check B Reminder About Why EVs Are Safe C Window Clings D Covid Shot,7:A Jack Dorsey B Mark Zuckerberg C Bill Gates D Kash Patel,
8:A Mirai B Clarity C Freestyle D Million Dollar Baby,9:A Myth B Twitter Livestream C Virus D Chan For White Supremacists,10:A Starships B Vampire Bats C Angels D Airships,11:A12 Days B5 Days C101 Days D9 Days,12:A NATOs Trump Whisperer B Wegovy C Long Covid D The Last Pontiac Ever Made,13:A Chlorine B A Bubble Bath C Windex D Communism Being The Right Thing In America,14:A Booze B PEDs Given To Joe Biden C BRICS D Alcohol,
15:A Monoxide B Dioxide C Trioxide D Quadrivalent,16:A The First Women President B Vladimir Putin  C Putin And His Head Investigator Feuding D Lauren Daegals Light Of The World]
covid strings21 sentence =[covid would be even less of a miracle than putin and his head investigator feuding]
covid strings scrambled phraselist21=[noires deen ratxe ovicd tosh,5+yads+fo+naltionsoi,afke+lilb+tages+croimhip]
userin.select team
import meta.
class myclass
constructor(non-concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else
prompt 
log
myclass=new.myclass(concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else
prompt 
log
import syntax
public.boolean isscramble
if (s1.length())!=s2.length()or s3.length()
return false
if (s1.length()) ==s2 or s3 
return true
char[]arr1=s1.tochararray
char[]arr2=s2.tochararray
char [] arr3=s3.tochararray
arrays.sort (arr1)
arrays.sort(arr2)
arrays.sort(arr3)
if(!new string(arr1).equals(new string (arr2)))
return false
for(int i=1; i<s1.length();i++)} 
string11=s1.substring(0,i)
string12=s1.substring(i,s1.length()-i);
string 13=s1.substring(i,s1.length()-i());
string14=s1.substring(0,s1.length()-i s1.length());
strings21=s2.substring(0,i)
string22=s2.substring(0,s2.length()-i);
string23=s2.substring(0,s2.length()-i ());
string24=s2.substring(0,s2.length()-i s2.length());
string31=s3.substring(0,i)
string32=s3.substring(0,s3.length()-i)
string33=s3.substring(0,s3.length()-i());
string34=s3.substring(0,s3.length()-i s3.length());
substring(start,end)
userin.multiple choice
if selectedanswer==correct answer:
return true
else:
return false
if selectedanswer=not correct
return false
else 
return true





